name: Build NeoForge mod with Gradle
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Extract build version information
      id: ref
      run: .github/extract_refs.sh
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        check-latest: true
    - name: Compile with Gradle
      run: ./gradlew build
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WFGM-artifacts-${{ steps.ref.outputs.branch }}
        path: build/libs/*.jar
